name: CI

on:
  schedule:
    - cron: "35 23 * * *"
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run test script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        git config user.name "bot"
        git config user.email "<>"
        git remote set-url origin https://mrsmsn:${{ secrets.GITHUB_TOKEN }}@github.com/mrsmsn/daily-workflow
        git branch
        git checkout master
        git branch
        echo hello >> README.md
        git add .
        git commit -m "update!"
        git push origin master

